### ISSUE TITLE
How to change SciChart background color

### ISSUE THREAD

**Issue by ashishkumarvaishnav** [ABTSoftware/SciChart.Android.Examples#12]
I want to change background color black to white.

**Comment by jinoralen** [comment]
Hi there. 

The easiest ways would be to create custom theme for chart using ThemeManager API. 

Please take a look on our [documentation](https://www.scichart.com/documentation/android/current/webframe.html#ThemeManager%20API.html) and [example in app](https://github.com/ABTSoftware/SciChart.Android.Examples/blob/SciChart_v4_Release/Examples/app/src/main/java/com/scichart/examples/fragments/CustomThemeFragment.java). You need to change sciChartBackground to change background for entire chart and renderableSeriesAreaFillColor and renderableSeriesAreaBorderColor to change fill and border color for center area of chart

Is this suitable for your needs?

**Comment by ashishkumarvaishnav** [comment]
Yes. 
Thank you so much.
