### ISSUE TITLE
MajorTicks方向

### ISSUE THREAD

**Issue by Demonhuang** [ABTSoftware/SciChart.Android.Examples#13]
有没有能设置MajorTicks方向的方向

**Comment by jinoralen** [comment]
Have you tried to [setFlipCoordinates](https://www.scichart.com/documentation/android/latest/api/charting/com.scichart.charting.visuals.axes.IAxisCore.html#com_scichart_charting_visuals_axes_IAxisCore_setFlipCoordinates_boolean_) to change flip direction of ticks?

**Comment by Demonhuang** [comment]
> 

现在Y周MajorTicks的刻度方向是向下的，有没有方法能让它向上，也就是在表格里，设置了setFlipCoordinates并不能解决我的问题

**Comment by Demonhuang** [comment]
> Have you tried to [setFlipCoordinates](https://www.scichart.com/documentation/android/latest/api/charting/com.scichart.charting.visuals.axes.IAxisCore.html#com_scichart_charting_visuals_axes_IAxisCore_setFlipCoordinates_boolean_) to change flip direction of ticks?
现在Y轴MajorTicks的刻度方向是向下的，有没有方法能让它向上，也就是在表格里，设置了setFlipCoordinates并不能解决我的问题

**Comment by jinoralen** [comment]
I'm afraid I don't understand what the problem is. You can FlipCoordinates independently for each axis and change tick direction from left-to-right to right-to-left for horizontal axes(XAxis) and from bottom-to-top to top-to-bottom for vertical axis(YAxis). So I want to ask you to provide more detailed description of problem so I could understand what you're trying to achieve ( e.g. code samples, screenshots/videos of current output vs what you are trying to achieve ), because otherwise I won't be able to suggest anything.

**Comment by Demonhuang** [comment]
> I'm afraid I don't understand what the problem is. You can FlipCoordinates independently for each axis and change tick direction from left-to-right to right-to-left for horizontal axes(XAxis) and from bottom-to-top to top-to-bottom for vertical axis(YAxis). So I want to ask you to provide more detailed description of problem so I could understand what you're trying to achieve ( e.g. code samples, screenshots/videos of current output vs what you are trying to achieve ), because otherwise I won't be able to suggest anything.

hello , i want to this result 
![image](https://user-images.githubusercontent.com/11385157/169478016-12c16869-52f6-4efa-8e2e-b6beda5874ef.png)

**Comment by Demonhuang** [comment]
[](url)

> I'm afraid I don't understand what the problem is. You can FlipCoordinates independently for each axis and change tick direction from left-to-right to right-to-left for horizontal axes(XAxis) and from bottom-to-top to top-to-bottom for vertical axis(YAxis). So I want to ask you to provide more detailed description of problem so I could understand what you're trying to achieve ( e.g. code samples, screenshots/videos of current output vs what you are trying to achieve ), because otherwise I won't be able to suggest anything.

![image](https://user-images.githubusercontent.com/11385157/169478408-48ae0234-e838-4e87-b552-843676ddb5ae.png)

**Comment by jinoralen** [comment]
You can try to add secondary xAxis and [set IsCenterAxis=true for it](https://www.scichart.com/documentation/android/current/webframe.html#Chart%20Layout%20-%20Placing%20Axis%20Central%20in%20the%20Chart.html) to place it at the center of chart. Then you can hide everything except labels for default axis and everything except major ticks for secondary axis. I've modified our [LineChartFragment](https://github.com/ABTSoftware/SciChart.Android.Examples/blob/SciChart_v4_Release/app/src/main/java/com/scichart/examples/fragments/examples2d/basicChartTypes/LineChartFragment.java) to show how to do this:

```java
    @Override
    protected void initExample(@NonNull SciChartSurface surface) {
        final IAxis xAxis = sciChartBuilder.newNumericAxis().withGrowBy(0.1d, 0.1d).withVisibleRange(1.1, 2.7).withDrawMinorTicks(false).withDrawMajorTicks(false).withDrawMajorBands(false).withDrawMajorGridLines(false).withDrawMinorGridLines(false).build();
        final IAxis secondaryXAxis = sciChartBuilder.newNumericAxis().withIsCenterAxis(true).withGrowBy(0.1d, 0.1d).withVisibleRange(xAxis.getVisibleRange()).withAxisId("SecondaryXAxis").withDrawLabels(false).withDrawMinorTicks(false).withDrawMajorBands(false).withDrawMinorGridLines(false).withDrawMinorGridLines(false).build();
        final IAxis yAxis = sciChartBuilder.newNumericAxis().withGrowBy(0.1d, 0.1d).withDrawLabels(false).withDrawMinorTicks(false).withDrawMajorTicks(false).withDrawMajorBands(false).withDrawMajorGridLines(false).withDrawMinorGridLines(false).build();

        final DoubleSeries fourierSeries = DataManager.getInstance().getFourierSeries(1.0, 0.1, 5000);
        final IXyDataSeries<Double, Double> dataSeries = sciChartBuilder.newXyDataSeries(Double.class, Double.class).build();
        dataSeries.append(fourierSeries.xValues, fourierSeries.yValues);

        final FastLineRenderableSeries rSeries = sciChartBuilder.newLineSeries().withDataSeries(dataSeries).withStrokeStyle(0xFF279B27, 1f, true).build();

        UpdateSuspender.using(surface, () -> {
            Collections.addAll(surface.getXAxes(), xAxis, secondaryXAxis);
            Collections.addAll(surface.getYAxes(), yAxis);
            Collections.addAll(surface.getRenderableSeries(), rSeries);
            Collections.addAll(surface.getChartModifiers(), sciChartBuilder.newModifierGroupWithDefaultModifiers().build());

            sciChartBuilder.newAnimator(rSeries).withSweepTransformation().withInterpolator(new DecelerateInterpolator()).withDuration(3000).withStartDelay(350).start();
        });
    }
```

<img width="649" alt="image" src="https://user-images.githubusercontent.com/1850908/169760599-28d5534b-f297-422a-86fd-c929e5ff6e35.png">


Is this suitable for your needs?

**Comment by Demonhuang** [comment]
this suitable is my need  but i want to set through a property ,Can you add corresponding methods？

**Comment by jinoralen** [comment]
I don't understand your requirement. As I understand output of chart is suitable for your need. Everything above is set through public API of SciChart and there is no need to modify source code of library. Can you explain?

**Comment by Demonhuang** [comment]
> I don't understand your requirement. As I understand output of chart is suitable for your need. Everything above is set through public API of SciChart and there is no need to modify source code of library. Can you explain?

hello ,we team is paying user, please tell me one by one of way to technical support  ?
