### ISSUE TITLE
A terrible showcase

### ISSUE THREAD

**Issue by zakrodionov** [ABTSoftware/SciChart.Android.Examples#9]
A terrible showcase, a mishmash of rxjava and binding. Make an illustrative example please.

**Comment by andyb1979** [comment]
Hey there, the SciChart Showcase is deprecated, the examples have been moved into the main examples suite here: 
https://github.com/ABTSoftware/SciChart.Android.Examples/tree/SciChart_v3_Release/Examples

Have you tried it out?

**Comment by andyb1979** [comment]
Has it helped? Check out the Audio Analyzer, ECG and Lidar demo here:
https://github.com/ABTSoftware/SciChart.Android.Examples/tree/SciChart_v3_Release/Examples/app/src/main/java/com/scichart/examples/fragments/showcase

There is also a trading demo in there 'Multi Pane Stock Charts' 

Best regards, 
Andrew
